name: model-validation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - nextflow
  - pyvista
  - meshio
  - conda-lock
  - conda
  - pip
  - pip:
      - "git+https://github.com/izus-fokus/snakemake-report-plugin-metadata4ing@maingith#egg=snakemake-report-plugin-metadata4ing"