name: postprocessing
channels:
  - conda-forge
  - defaults

channel_priority: strict

dependencies:
  - python=3.12
  - pint
  - pyvista
  - rdflib
  - matplotlib
  - pandas
  - pip
  - pip:
      - roc-validator
      - rohub 
