name: fenics_simulation
channels:
  - conda-forge

channel_priority: strict

dependencies:
  - python=3.12
  - fenics-dolfinx=0.9.*
  - libadios2=2.10.1
  - petsc4py
  - pint
  - python-gmsh
  - sympy
